### ISSUE TITLE
Add The Context to Play Music podcasts

### ISSUE THREAD

**Issue by SUPERCILEX** [artem-zinnatullin/TheContext-Podcast#46]
Since pocket cast is a paid app, I'd love it if you guys added this podcast to play music!

**Comment by artem-zinnatullin** [comment]
As far as I remember Play Music allows add only podcasts based in US..

Btw you can use any podcast player (there should be some free) and just add
it via link to the RSS feed (see readme).

**Comment by sockeqwe** [comment]
Yep, at the moment it Goople Play Music podcasts is available only in US and Canada.
But maybe an option for the future...

In the meantime, as already suggested by Artem, you can use basically every other podcast player. There are some on google play store. Some are free, some show advertisement etc.
This is a free one: https://play.google.com/store/apps/details?id=de.danoeh.antennapod
not the best UI but it's free.

Many podcast apps have a search function. Search for "The Context" or "androiddev" or "The Context #androiddev"
If still you can't find our podcast, usually podcast apps have a way to import a podcast manually by inserting the RSS Feed url. For our podcast please enter: https://raw.githubusercontent.com/artem-zinnatullin/TheContext-Podcast/master/feed.rss

**Comment by SUPERCILEX** [comment]
Thanks!

I had a thought though... What if I added the podcast to Play for you guys and then just transferred ownership? (Play Music is cool in that is uses the same sharing system as Google Drive for publishing podcasts)

If that still doesn't work, the podcast is licensed under the Apache license so doesn't that mean that I can just put the podcast there for you guys since the license gives anyone the right to copy the work?

PS: I really like Play Music because it automatically syncs of my podcasts offline (I know pocket cast does that too but I don't want to pay $4 for a podcast app). Also, I'm always just amazed at how good Google is at making the experience seamless from my phone to my laptop. 😄

**Comment by kboyarshinov** [comment]
@SUPERCILEX FYI here's another good free podcast app: https://play.google.com/store/apps/details?id=fm.player. Has also background sync feature.

**Comment by artem-zinnatullin** [comment]
I’ve looked into it and unfortunately, Google Play Music still doesn’t allow to add podcast from non US and listener can’t add it by feed url.

I’m afraid we’ll have problems with transferring ownership if you upload podcast for us…

On Mon, Jul 11, 2016 at 8:17 AM Kirill Boyarshinov

<
mailto:Kirill Boyarshinov <notifications@github.com>
> wrote:

https://github.com/SUPERCILEX
FYI here's another good free podcast app:
https://play.google.com/store/apps/details?id=fm.player
. Has also background sync feature.

—

You are receiving this because you commented.

Reply to this email directly,
https://github.com/artem-zinnatullin/TheContext-Podcast/issues/46#issuecomment-231644093
, or
https://github.com/notifications/unsubscribe/AA7B3KtKCSjDvUQrDlQb4Ok7G1nJ590cks5qUdICgaJpZM4JIXug
.

https://github.com/artem-zinnatullin/TheContext-Podcast/issues/46#issuecomment-231644093

**Comment by SUPERCILEX** [comment]
@kboyarshinov thanks for the podcast app! It's growing on me: it took a while to customize it to my liking, but I'm starting to really like it!

@artem-zinnatullin I've tried sharing the podcast with you (it's not published). You should be able to log from the email google sent you, if not, then :( I'll delete it and we'll have to wait for Google to expand their horizons to other countries.

**Comment by artem-zinnatullin** [comment]
Yeah, I saw email and was surprised :) I'll try it today!

**Comment by SUPERCILEX** [comment]
Awesome!

**Comment by artem-zinnatullin** [comment]
It says "Podcasts are not available in your country" when I try to verify
ownership, will try to do it from vpn today/tomorrow.

**Comment by SUPERCILEX** [comment]
On Android, I use cloudVPN.
