### ISSUE TITLE
Rename Markdown files so they're sorted by numbers

### ISSUE THREAD

**Issue by vanniktech** [artem-zinnatullin/TheContext-Podcast#88]
It'd be nice if README's would be sorted by numbers.

```
Episode_001.md
Episode_002.md
Episode_010.md
Episode_099.md
Episode_100.md
Episode_999.md
```

**Comment by sockeqwe** [comment]
Sounds reasonable. I have to check if this breaks some podcast players
relaying on some static links from our rss feed though.

Also, in the (hopefully near) future we would like to have a website.

Niklas Baudy <notifications@github.com> schrieb am Mi., 14. März 2018,
04:14:

**Comment by artem-zinnatullin** [comment]
Yeah, that was design mistake i've made with file names…

As Hannes pointed we might have problems with renaming them because file name is part of links in rss feed (ie in Episode description) 

However we might workaround that by updating those links in rss feed right? I think unless you change `guid` of the `<item>` it should be ok

---

Not sure why do we need website for that tho, it's a pain to maintain :)

**Comment by sockeqwe** [comment]
website (with integrated audio player) makes it easier to share new
episodes, i.e. androidweekly, reddit and so on, and once we have our CI
system runnimg, autogenerating this should be to easy (almost zero
maintainance costs)

Artem Zinnatullin :slowpoke: <notifications@github.com> schrieb am Mo., 19.
März 2018, 07:22:
